"""social media and followed social media table added.

Revision ID: 0aff6f0bc151
Revises: 1cd4c4094a5d
Create Date: 2023-02-06 15:31:08.590871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aff6f0bc151'
down_revision = '1cd4c4094a5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_media',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('column_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followed_social_media',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('facebook_followed', sa.Boolean(), nullable=True),
    sa.Column('youtube_followed', sa.Boolean(), nullable=True),
    sa.Column('twitter_followed', sa.Boolean(), nullable=True),
    sa.Column('whatsapp_followed', sa.Boolean(), nullable=True),
    sa.Column('linkedin_followed', sa.Boolean(), nullable=True),
    sa.Column('telegram_followed', sa.Boolean(), nullable=True),
    sa.Column('instagram_followed', sa.Boolean(), nullable=True),
    sa.Column('discord_followed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('users_id')
    )
    op.alter_column('merchant_profile', 'authorized_person',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant_profile', 'authorized_person',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_table('followed_social_media')
    op.drop_table('social_media')
    # ### end Alembic commands ###
