"""Added sales_person_id to merchant_profile

Revision ID: 1cd4c4094a5d
Revises: c3eca123ac39
Create Date: 2023-01-27 15:46:24.987082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd4c4094a5d'
down_revision = 'c3eca123ac39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_profile', sa.Column('sales_person_id', sa.String(length=10), nullable=True))
    op.create_unique_constraint('unique_user_role', 'user_roles', ['users_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_column('merchant_profile', 'sales_person_id')
    # ### end Alembic commands ###
