"""Initial Migration

Revision ID: c3eca123ac39
Revises: 
Create Date: 2023-01-24 14:22:11.314827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3eca123ac39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_category',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('country',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('flag', sa.String(length=1024), nullable=True),
    sa.Column('country_code', sa.String(length=16), nullable=False),
    sa.Column('currency_symbol', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('id_proofs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_type')
    )
    op.create_table('roles',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('referral_code', sa.String(length=10), nullable=False),
    sa.Column('referred_by', sa.String(length=10), nullable=True),
    sa.Column('pin', sa.String(length=200), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(length=200), nullable=True),
    sa.Column('token_expired', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('referral_code'),
    sa.UniqueConstraint('token')
    )
    op.create_table('channel_partner',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('FEMALE', 'MALE', 'OTHER', name='gendertype'), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('alt_name', sa.String(length=100), nullable=True),
    sa.Column('address1', sa.String(length=100), nullable=False),
    sa.Column('address2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('district', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('locality', sa.String(length=20), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('pan_card_doc', sa.String(length=100), nullable=True),
    sa.Column('aadhaar_card_doc', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_partner_id'), 'channel_partner', ['id'], unique=False)
    op.create_table('consumer_profile',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('FEMALE', 'MALE', 'OTHER', name='gendertype'), nullable=False),
    sa.Column('address1', sa.String(length=100), nullable=True),
    sa.Column('address2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('district', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('current_location', sa.JSON(), nullable=True),
    sa.Column('device_platform', sa.Enum('ANDROID', 'IOS', name='devicetype'), nullable=True),
    sa.Column('fcm_token', sa.String(length=1024), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('phone_number_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('users_id')
    )
    op.create_table('merchant_profile',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('merchant_account_number', sa.String(length=50), nullable=True),
    sa.Column('merchant_name', sa.String(length=50), nullable=True),
    sa.Column('authorized_person', sa.String(length=50), nullable=False),
    sa.Column('kyc_doc_type', sa.String(length=50), nullable=True),
    sa.Column('kyc_doc', sa.String(length=100), nullable=True),
    sa.Column('channel_partner_id', sa.Integer(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('FEMALE', 'MALE', 'OTHER', name='gendertype'), nullable=False),
    sa.Column('profile_image', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('users_id')
    )
    op.create_table('merchants_country_id_proofs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('id_proof_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['merchants_country_id_proofs.id'], ),
    sa.ForeignKeyConstraint(['id_proof_id'], ['id_proofs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_bank_details',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('current_account_name', sa.String(length=50), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('ifsc_number', sa.String(length=20), nullable=False),
    sa.Column('branch_name', sa.String(length=50), nullable=False),
    sa.Column('bank_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id')
    )
    op.create_table('merchant_business_info',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('registered_business_name', sa.String(length=255), nullable=False),
    sa.Column('registered_business_number', sa.String(length=32), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('business_description', sa.String(length=255), nullable=False),
    sa.Column('business_category', sa.Integer(), nullable=False),
    sa.Column('dba', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('operating_address', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('operating_postal_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['business_category'], ['business_category.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id')
    )
    op.create_table('merchant_tax_information',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('name_on_pan', sa.String(length=50), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('pan_doc', sa.String(length=1024), nullable=True),
    sa.Column('gstin_doc', sa.String(length=1024), nullable=True),
    sa.Column('tan_doc', sa.String(length=1024), nullable=True),
    sa.Column('id_proof', sa.String(length=100), nullable=True),
    sa.Column('id_proof_type', sa.Integer(), nullable=True),
    sa.Column('id_proof_doc', sa.String(length=1024), nullable=True),
    sa.Column('address_proof', sa.String(length=50), nullable=True),
    sa.Column('address_proof_type', sa.Integer(), nullable=True),
    sa.Column('address_proof_doc', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['address_proof_type'], ['id_proofs.id'], ),
    sa.ForeignKeyConstraint(['id_proof_type'], ['id_proofs.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id')
    )
    op.create_table('store',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('store_name', sa.String(length=50), nullable=False),
    sa.Column('owner_name', sa.String(length=20), nullable=False),
    sa.Column('business_email', sa.String(length=50), nullable=False),
    sa.Column('business_phone', sa.String(length=20), nullable=False),
    sa.Column('address1', sa.String(length=100), nullable=False),
    sa.Column('address2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('district', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('shop_image', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store')
    op.drop_table('merchant_tax_information')
    op.drop_table('merchant_business_info')
    op.drop_table('merchant_bank_details')
    op.drop_table('user_roles')
    op.drop_table('merchants_country_id_proofs')
    op.drop_table('merchant_profile')
    op.drop_table('consumer_profile')
    op.drop_index(op.f('ix_channel_partner_id'), table_name='channel_partner')
    op.drop_table('channel_partner')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('id_proofs')
    op.drop_table('country')
    op.drop_table('business_category')
    # ### end Alembic commands ###
